homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Makes the lovelace frontend be editable from the ui-lovelace.yaml file
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
    api_password: !secret api_password
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  purge_keep_days: 1
  purge_interval: 1

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: mqtt
    name: "Living Room Temp"
    state_topic: "tele/sonoffTH/SENSOR"
    unit_of_measurement: "°C"
    qos: 1
    value_template: "{{ value_json.AM2301.Temperature }}"
  - platform: mqtt
    name: "Living Room Humidity"
    state_topic: "tele/sonoffTH/SENSOR"
    unit_of_measurement: "%"
    qos: 1
    value_template: "{{ value_json.AM2301.Humidity }}"

switch:
  - platform: mqtt
    name: "Extra"
    command_topic: "cmnd/sonoff/power"
    state_topic: "stat/sonoff/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Living Room Lamp"
    command_topic: "cmnd/sonoffTH/power"
    state_topic: "stat/sonoffTH/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Bedroom Lamp"
    command_topic: "cmnd/sonoffS20/power"
    state_topic: "stat/sonoffS20/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# To expose temperature to Google Home
climate:
  - platform: generic_thermostat
    name: Living Room Temperature
    heater: input_boolean.fake_heater
    target_sensor: sensor.living_room_temp
    initial_operation_mode: "off"
    target_temp: 21

# Faking the thermostat
input_boolean:
  fake_heater:
    name: Fake Heater
    icon: mdi:toggle-switch-off
    initial: off

# Z-wave setup
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret network_key

# Device Tracking / Presence Detection
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
    consider_home: 0:15:00
    interval_seconds: 30

# Sonos
sonos:
  media_player:
    interface_addr: 192.168.86.44
    hosts: 
      - 192.168.86.51 #Beam - Living Room
      - 192.168.86.52 #Play:1 - Living Room


# Google Wifi and Speedtest
sensor googlewifi:
  - platform: google_wifi

#SPEEDTEST	
sensor speedtest:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 14
    - 16
    - 18
    - 20
    - 22
  monitored_conditions:
    - ping
    - download
    - upload

# Text to speech
tts:
  - platform: google

# Cloud - Google Home Device Interface Setup
cloud:
  google_actions:
    filter:
      include_entities:
        - switch.aeotec_zw140_dual_nano_switch_switch
        - switch.aeotec_zw140_dual_nano_switch_switch_2
        - switch.aeotec_zw139_nano_switch_switch
        - climate.living_room_temperature
        - switch.living_room_lamp
        - switch.bedroom_lamp
        - switch.extra
      exclude_entities:
        - input_boolean.fake_heater
      exclude_domains:
        - switch
        - media_player
        - group
    entity_config:
      switch.aeotec_zw140_dual_nano_switch_switch:
        name: Living Room Ceiling Light
        room: living room
      switch.aeotec_zw140_dual_nano_switch_switch_2:
        name: Kitchen Ceiling Light
        room: kitchen
      switch.aeotec_zw139_nano_switch_switch:
        name: Bedroom Ceiling Light
        room: bedroom
      climate.living_room_temperature:
        name: Living Room Temperature
        room: living room
      switch.living_room_lamp:
        name: Living Room Lamp
        room: living room
      switch.bedroom_lamp:
        name: Bedroom Lamp
        room: bedroom
      switch.extra:
        name: Extra

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
