homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 78
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

http:
  base_url: https://preference.duckdns.org:433
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# https://www.home-assistant.io/integrations/default_config/
default_config:

lovelace:
  mode: yaml

# Discover some devices automatically
discovery:
  ignore:
    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_keep_days: 1
  purge_interval: 1

# Changes switches to light/lamps
light:
  - platform: switch
    name: Basement Lamp
    entity_id: switch.ikea_plug_1
  - platform: switch
    name: Bedroom Lamp
    entity_id: switch.sonoffth_bedroom

# Creates thermostats
climate:
  - platform: generic_thermostat
    name: Bedroom
    heater: switch.sonoffs2x_bedroom
    target_sensor: sensor.sonoffth_bedroom_th_bedroom_temperature
    min_temp: 15
    max_temp: 25
  - platform: generic_thermostat
    name: Basement
    heater: switch.sonoffs2x_basement
    target_sensor: sensor.aeon_labs_zw100_multisensor_6_temperature
    min_temp: 15
    max_temp: 25

# Z-wave setup
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00 #/dev/ttyACM0
  network_key: !secret network_key

# Tracks devices with Person
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
    home_interval: 10
    interval_seconds: 30
    consider_home: 0:05:00
    new_device_defaults:
      track_new_devices: false
  - platform: google_maps
    username: homeassistant.preference@gmail.com

# Sensors
sensor:
  # Google Wifi and Speedtest
  - platform: google_wifi
    host: 192.168.86.1
  # Entur
  - platform: entur_public_transport
    name: Transport
    expand_platforms: true
    show_on_map: true
    stop_ids:
      - NSR:StopPlace:58280
      - NSR:StopPlace:3657
  - platform: google_fit
    name: Christian
    client_id: !secret google_fit_client_id
    client_secret: !secret google_fit_client_secret

#SPEEDTEST
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# Xiaomi Mi Roborock S50 Vacuum
vacuum:
  - platform: xiaomi_miio
    host: 192.168.86.61
    token: !secret roborock_token

# IFTTT
ifttt:
  key: !secret ifttt_api

# Google Assistant / Home
google_assistant:
  project_id: home-assistant-267320
  service_account: !include serv_acc_assistant.json
  report_state: true
  entity_config:
    switch.shelly2_basement_1:
      name: Basement Light
      expose: true
      room: Basement
    switch.shelly2_stairs_1:
      name: Stairs Light
      expose: true
      room: Basement
    light.basement_lamp:
      name: Basement Lamp
      expose: true
      room: Basement
    light.ikea_bulb_bedroom_1:
      name: Bedroom Light
      expose: true
      room: Bedroom
    light.bedroom_lamp:
      name: Bedroom Lamp
      expose: true
      room: Bedroom
    climate.bedroom:
      expose: true
      room: Bedroom
    climate.basement:
      expose: true
      room: Basement
  expose_by_default: false

# Withings / Health Mate
# Example configuration.yaml entry
withings:
  client_id: !secret client_id
  client_secret: !secret consumer_secret
  profiles:
    - !secret user_profile_name

# Shelly
shelly:
  discovery: true #add all devices (default)

zone: !include zones.yaml
automation: !include automations.yaml
