homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Makes the lovelace frontend be editable from the ui-lovelace.yaml file
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
    api_password: !secret api_password
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  purge_keep_days: 1
  purge_interval: 1

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  google_actions:
    filter:
      include_entities:
        - switch.aeotec_zw140_dual_nano_switch_switch
        - switch.aeotec_zw140_dual_nano_switch_switch_2
        - switch.aeotec_zw139_nano_switch_switch
      exclude_domains:
        - switch
        - media_player
        - group
    entity_config:
      switch.aeotec_zw140_dual_nano_switch_switch:
        name: Living Room
        room: living room
      switch.aeotec_zw140_dual_nano_switch_switch_2:
        name: Kitchen
        room: kitchen
      switch.aeotec_zw139_nano_switch_switch:
        name: Bedroom
        room: bedroom

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
