# Resources
resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module

title: Home
views:
  - title: Home
    cards:
      - type: entities
        title: All Switches
        show_header_toggle: true
        entities:
          - switch.aeotec_zw139_nano_switch_switch
          - switch.aeotec_zw140_dual_nano_switch_switch
          - switch.aeotec_zw140_dual_nano_switch_switch_2
          - switch.aeotec_zw140_dual_nano_switch_switch_3
      - type: entities
        title: Media Players
        entities:
          - entity: media_player.everywhere
            type: custom:mini-media-player
            group: true
          - entity: media_player.living_room_tv
            type: custom:mini-media-player
            icon: mdi:television
            group: true
          - entity: media_player.living_room_speaker
            type: custom:mini-media-player
            name: Living Room Speaker
            icon: mdi:speaker
            hide_controls: true
            group: true
          - entity: media_player.hub
            type: custom:mini-media-player
            icon: mdi:tablet
            hide_controls: true
            group: true
          - entity: media_player.bedroom_speaker
            type: custom:mini-media-player
            icon: mdi:google-home
            hide_controls: true
            group: true
          
