# Resources
resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /community_plugin/entur-card/entur-card.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module

title: Home
views:
  #####################################################################################
  #  HOME # HOME # HOME # HOME # HOME # HOME # HOME # HOME HOME # HOME HOME # HOME    #
  #####################################################################################
  - path: default_view
    title: Home
    icon: mdi:home
    cards:
      - type: entity-filter
        card:
          type: glance
          show_state: false
          show_name: true
        entities:
          - person.christian
          - person.sebastian
          - person.daniel
          - person.carina
          - person.trond
        state_filter:
          - home
        show_empty: false
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:mini-media-player
            entity: media_player.sonos_dining_room
            hide:
              power: true
              icon: true
              source: true
            speaker_group:
              platform: sonos
              show_group_count: true
              entities:
                - entity_id: media_player.sonos_dining_room
                  name: Sonos Dining Room
                - entity_id: media_player.sonos_living_room
                  name: Sonos Living Room
          - entity: media_player.everywhere
            type: custom:mini-media-player
            artwork: cover
            group: true
            hide:
              controls: true
              source: true
              power_state: false
          - entity: media_player.kitchen_display
            type: custom:mini-media-player
            icon: mdi:tablet
            artwork: cover
            group: true
            hide:
              controls: true
              source: true
              power_state: false
          - entity: media_player.living_room_speaker
            type: custom:mini-media-player
            icon: mdi:google-home
            artwork: cover
            group: true
            hide:
              controls: true
              source: true
              power_state: false
      - type: entities
        entities:
          - entity: binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor_2
            name: Hallway Door
            secondary_info: last-changed

      - type: glance
        entities:
          - sensor.sonoffth_bedroom_th_bedroom_temperature
          - sensor.aeon_labs_zw100_multisensor_6_temperature
          - sensor.fibaro_system_fgk101_door_opening_sensor_temperature
      - type: custom:entur-card
        show_clock: false
        show_next: true
        show_human: true
        show_extra_departures: true
        entities:
          - entity: sensor.transport_jar_platform_1
            name: T-bane
          - entity: sensor.transport_jar_platform_6531
            name: Trikk
          - entity: sensor.transport_jar_bru_platform_6515
            name: Buss

  #####################################################################################
  #  BEDROOM # BEDROOM # BEDROOM # BEDROOM # BEDROOM # BEDROOM # BEDROOM # BEDROOM    #
  #####################################################################################
  - path: bedroom
    title: Bedroom
    icon: mdi:hotel
    cards:
      - type: entities
        entities:
          - entity: media_player.bedroom_display
            type: custom:mini-media-player
            icon: mdi:tablet
            artwork: cover
            group: true
            hide:
              source: true
              power_state: false
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.ikea_bulb_bedroom_1
          - light.bedroom_lamp
      - type: thermostat
        entity: climate.bedroom
      - type: horizontal-stack
        cards:
          - type: "custom:mini-graph-card"
            entity: sensor.sonoffth_bedroom_th_bedroom_temperature
            name: Temperature
            line_color: "#3498db"
            line_width: 8
          - type: "custom:mini-graph-card"
            entity: sensor.sonoffth_bedroom_th_bedroom_humidity
            device_class: humidity
            name: Humidity
            line_color: "#e74c3c"
            line_width: 8
  #####################################################################################
  #     BASEMENT # BASEMENT # BASEMENT # BASEMENT # BASEMENT # BASEMENT # BASEMENT    #
  #####################################################################################
  - path: basement
    title: Basement
    icon: mdi:home-floor-b
    cards:
      - type: entities
        entities:
          - entity: media_player.basement_speaker
            type: custom:mini-media-player
            icon: mdi:dots-horizontal-circle
            artwork: cover
            group: true
            hide:
              source: true
              power_state: false
          - entity: media_player.basement_tv
            type: custom:mini-media-player
            icon: mdi:television
            artwork: cover
            group: true
            hide:
              source: true
              power_state: false
      - type: entities
        entities:
          - light.basement_lamp
          - switch.shelly2_basement_1
          - switch.shelly2_stairs_1
      - type: thermostat
        entity: climate.basement
      - type: horizontal-stack
        cards:
          - type: "custom:mini-graph-card"
            entity: sensor.aeon_labs_zw100_multisensor_6_temperature
            name: Temperature
            line_color: "#3498db"
            line_width: 8
          - type: "custom:mini-graph-card"
            entity: sensor.aeon_labs_zw100_multisensor_6_relative_humidity
            device_class: humidity
            name: Humidity
            line_color: "#e74c3c"
            line_width: 8
  #####################################################################################
  #  VACUUM # VACUUM # VACUUM # VACUUM # VACUUM # VACUUM # VACUUM # VACUUM # VACUUM   #
  #####################################################################################
  - path: vacuum
    title: Vacuum
    icon: mdi:robot-vacuum
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        image: /local/community/lovelace-xiaomi-vacuum-card/vacuum.png
        name: Fido
        vendor: xiaomi
        buttons:
          start: true
          stop: true
          locate: true
        icons:
          start: mdi:play
          stop: mdi:stop
        labels:
          status: Status
          battery: Battery
          mode: Mode
          main_brush: Main Brush
          side_brush: Side Brush
          filter: Filter
          sensor: Sensor

  #####################################################################################
  # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP # MAP #
  #####################################################################################
  - path: map
    title: Map
    icon: mdi:map
    panel: true
    cards:
      - type: map
        aspect_ratio: default
        default_zoom: 12
        geo_location_sources: [all]
        entities:
          - zone.home
          - zone.work
          - person.christian

  #####################################################################################
  #   EXTRA # EXTRA # EXTRA # EXTRA # EXTRA # EXTRA # EXTRA # EXTRA # EXTRA # EXTRA   #
  #####################################################################################
  - path: extra
    title: Extra
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - zwave.aeon_labs_zw100_multisensor_6
          - sensor.aeon_labs_zw100_multisensor_6_alarm_level
          - sensor.aeon_labs_zw100_multisensor_6_alarm_type
          - sensor.aeon_labs_zw100_multisensor_6_battery_level
          - sensor.aeon_labs_zw100_multisensor_6_burglar
          - sensor.aeon_labs_zw100_multisensor_6_luminance
          - sensor.aeon_labs_zw100_multisensor_6_relative_humidity
          - binary_sensor.aeon_labs_zw100_multisensor_6_sensor
          - sensor.aeon_labs_zw100_multisensor_6_sourcenodeid
          - sensor.aeon_labs_zw100_multisensor_6_temperature
          - sensor.aeon_labs_zw100_multisensor_6_ultraviolet

  #####################################################################################
  # INFORMATION # INFORMATION # INFORMATION # INFORMATION # INFORMATION # INFORMATION #
  #####################################################################################
  - path: information
    title: Information
    icon: mdi:information
    cards:
      - type: entities
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.google_wifi_status
          - sensor.google_wifi_uptime
          - sensor.google_wifi_last_restart
          - sensor.google_wifi_current_version
          - sensor.google_wifi_local_ip
          - sensor.google_wifi_new_version
      - type: entities
        title: Prescence
        show_header_toggle: false
        entities:
          - entity: person.christian
          - entity: person.sebastian
          - entity: person.daniel
          - entity: person.carina
          - entity: person.trond

  #####################################################################################
  # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT # FIT #
  #####################################################################################
  - path: fit
    title: Fitness
    icon: mdi:google-fit
    cards:
      - type: entities
        title: Health
        show_header_toggle: false
        entities:
          - sensor.christian_height
          - sensor.withings_weight_kg_christian_nyvoll
          - sensor.christian_steps
          - sensor.christian_distance
          - sensor.christian_move_time
          - sensor.withings_fat_ratio_pct_christian_nyvoll
          - sensor.withings_heart_pulse_bpm_christian_nyvoll
          - sensor.christian_calories
