# Resources
resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module

title: Home
views:
  - path: default_view
    title: Home
    icon: mdi:home
    #badges:
      #- device_tracker.preference_oneplus
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Lights
            show_header_toggle: true
            entities:
              - entity: switch.aeotec_zw139_nano_switch_switch
                name: Bedroom Ceiling Light
              - entity: switch.aeotec_zw140_dual_nano_switch_switch
                name: Living Room Ceiling Light
              - light.bedroom_lamp
              - entity: switch.aeotec_zw140_dual_nano_switch_switch_2
                name: Kitchen Ceiling Light
              - light.living_room_lamp
          - type: horizontal-stack
            cards:
              - type: "custom:mini-graph-card"
                entity: sensor.living_room_temp
                name: Living Room
                line_color: '#3498db'
                line_width: 8
              - type: "custom:mini-graph-card"
                entity: sensor.living_room_humidity
                device_class: humidity
                name: Humidity
                line_color: '#e74c3c'
                line_width: 8
              - type: "custom:mini-graph-card"
                entity: sensor.fibaro_system_fgk101_door_opening_sensor_temperature
                name: Bedroom
                line_width: 8
                style:
                  font-size: 50%
      - type: glance
        # show_name: false
        entities:
          - entity: device_tracker.oneplus_6_lan
          - entity: device_tracker.daniels_iphone_lan
          - entity:  device_tracker.galaxy_a8_2018_lan
          - entity: device_tracker.android_1c44494142cafe49_lan

      #- type: iframe
       # url: https://www.yr.no/sted/Norge/Tr%C3%B8ndelag/Trondheim/Trondheim/meteogram.png
        # aspect_ratio: 50%
      - type: entities
        title: Media Players
        show_header_toggle: false
        entities:
          - entity: media_player.living_room
            type: custom:mini-media-player
            name: Sonos
            icon: mdi:cassette
            hide_power: true
            group: true
            #sonos_grouping:
             # - entity_id: media_player.living_room
             #   name: Beam
             # - entity_id: media_player.kitchen
             #   name: Play:1
          - type: divider
            style:
              height: 2px
              background-color: "#dddddd"
              margin-top: 40px
              margin-bottom: 40px
          - entity: media_player.everywhere
            type: custom:mini-media-player
            hide_power: true
            group: true
          - entity: media_player.living_room_tv
            type: custom:mini-media-player
            icon: mdi:television
            group: true
          - entity: media_player.living_room_speaker
            type: custom:mini-media-player
            name: Living Room Speaker
            icon: mdi:speaker
            hide_controls: true
            group: true
          - entity: media_player.googlehomehub7023
            type: custom:mini-media-player
            icon: mdi:tablet
            hide_controls: true
            group: true
          - entity: media_player.bedroom_speaker
            type: custom:mini-media-player
            icon: mdi:google-home
            hide_controls: true
            group: true
  - path: vacuum
    title: Vacuum
    icon: mdi:robot-vacuum
    cards:
      - type: entities
        title: Fido
        show_header_toggle: false
        entities:
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: Xiaomi Roborock S50
      - type: glance
        show_name: false
        show_state: false
        entities:
          - entity: vacuum.xiaomi_vacuum_cleaner
            tap_action: 
                action: call-service
                service: vacuum.start
                service_data:
                    entity_id: vacuum.xiaomi_vacuum_cleaner
            icon: mdi:play
          - entity: vacuum.xiaomi_vacuum_cleaner
            tap_action: 
                action: call-service
                service: vacuum.pause
                service_data:
                    entity_id: vacuum.xiaomi_vacuum_cleaner
            icon: mdi:pause
          - entity: vacuum.xiaomi_vacuum_cleaner
            tap_action: 
                action: call-service
                service: vacuum.return_to_base
                service_data:
                    entity_id: vacuum.xiaomi_vacuum_cleaner
            icon: mdi:home
          - entity: vacuum.xiaomi_vacuum_cleaner
            tap_action: 
                action: call-service
                service: vacuum.locate
                service_data:
                    entity_id: vacuum.xiaomi_vacuum_cleaner
            icon: mdi:map-marker
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - entity: automation.clean_kitchen
            name: Clean Kitchen
          - entity: automation.clean_living_room
            name: Clean Living Room
          - entity: automation.clean_bedroom
            name: Clean Bedroom
  - path: map
    title: Map
    icon: mdi:map
    cards:
      - type: map
        entities:
          - device_tracker.preference_oneplus
          - device_tracker.emily_p10
          - zone.home
          - zone.school
          - zone.work
  - path: extra
    title: Extra
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - entity: switch.extra_2
            name: TV
          - entity: switch.extra_1
            name: Sonos  
          - switch.extra
  - path: information
    title: Information
    icon: mdi:information
    cards:
      - type: entities
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.google_wifi_status
          - sensor.google_wifi_uptime
          - sensor.google_wifi_last_restart
          - sensor.google_wifi_current_version
          - sensor.google_wifi_local_ip
          - sensor.google_wifi_new_version
      - type: entities
        title: Prescence
        show_header_toggle: false
        entities:
          - entity: device_tracker.oneplus_6_lan
          - entity: input_boolean.guest
          - entity: input_boolean.home_occupied
          - entity: input_boolean.vacuumed_today
      - type: entities
        title: Door
        show_header_toggle: false
        entities:
        - entity: binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor_2
          name: Bedroom Door
          secondary_info: last-changed
          device_class: door

          
